FROM python:3.7.7

RUN pip3 install numpy
RUN pip3 install numba
RUN pip3 install cython

ENV PATH="/count-areas:${PATH}"
#ADD . /count-areas
VOLUME /Users/fullname/Downloads/count-areas-cython
WORKDIR /count-areas
